### ISSUE TITLE
Do not restrict dependencies to a specific minor version

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-mongo-libs#13]
I needed to test if a bug occurs on latest minor version (1.0.4) of `doctrine/mongodb-odm` bundle.
I can't update to this version because the dependencie is strict to `1.0.3`.

The dependencies should allow to use minor revision of bundles. IMHO, this is important as you can't deploy security advisory fix. We will depend on your reactivity of releasing a version with updated dependencies.

**Comment by nicolasThal** [comment]
To insure the stability of the platform, we need to test the fixes before releasing the product with it.
